# Google Auth Configs
CLIENT_ID = 'INSERT YOUR GOOGLE CLIENT ID HERE'
CLIENT_SECRET = 'INSERT YOUR GOOGLE CLIENT SECRET HERE'
REFRESH_TOKEN = 'INSERT YOUR GOOGLE REFRESH TOKEN HERE'

# Playlist Configs
PLAYLISTS = {'PLAYLIST_NAME_HERE': 'PLAYLIST_ID_HERE',
             'PLAYLIST2_NAME_HERE': 'PLAYLIST2_ID_HERE'
             }

# Directory configs
VIDEOS_DIR = './output/videos/'

# DO NOT CHANGE THE DIRECTORY BELOW
# IF YOU REALLY NEED TO CHANGE READ THE PROJECT'S PAGE ON GITHUB
OUTPUT_DIR = './output/'
